stages:          # List of stages for jobs, and their order of execution
  - deploy 

deploy:      # This job runs in the deploy stage.
  stage: deploy
  script:
    - docker-compose up -d --force-recreate
  tags:
    - prodam_150
  only:
    - master  
