version: '3.3'

services:
  sapej_build:
    image: sapej_build
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sapej_build
    network_mode: bridge
    working_dir: /app
    command: bash -c 'npm install && npm run build'   
    volumes:
      - ./:/app
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'

  sapej:
    image: nginx:latest
    container_name: sapej
    restart: always
    ports:
      - '8282:80'
    volumes:
      - '/opt/sapej/dist/:/usr/share/nginx/html'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    network_mode: bridge
    depends_on:
      - sapej_build