version: '3.3'

services:
  sapej_build:
    image: node:16
    container_name: sapej_build
    network_mode: bridge
    working_dir: /app
    command: bash -c 'npm install && npm run build'
    environment:
      NODE_ENV: production
    volumes:
      - ./:/app
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'

  sapej:
    image: nginx:latest
    container_name: sapej
    ports:
      - '8282:80'
    volumes:
      - '/opt/sapej/dist/:/usr/share/nginx/html'
    network_mode: bridge
