export type Orgaos = {
  texto: string;
  value: number;
};

export const OrgaosSeeder: Array<Orgaos> = [
  { texto: "DPE", value: 1 },
  { texto: "Delegacia de Polícia", value: 2 },
  { texto: "FVS", value: 3 },
  { texto: "SPA", value: 4 },
  { texto: "TCE", value: 5 },
  { texto: "MPC", value: 6 },
  { texto: "MPE", value: 7 },
  { texto: "MPF", value: 8 },
  { texto: "MPT", value: 9 },
  { texto: "TCU", value: 10 },
  { texto: "Ministério da Saúde", value: 11 },
  { texto: "CRM", value: 12 },
  { texto: "CEMA", value: 13 },
  { texto: "DPU", value: 14 },
  { texto: "Casa Civil", value: 15 },
  { texto: "ALEAM", value: 16 },
  { texto: "SEINFRA", value: 17 },
  { texto: "Serviço Social", value: 18 },
  { texto: "SEJUSC", value: 19 },
  { texto: "SESAI", value: 20 },
  { texto: "HPS Platão Araújo", value: 21 },
  { texto: "HPS 28 de Agosto", value: 22 },
  { texto: "PGE", value: 23 },
  { texto: "CGE", value: 24 },
  { texto: "CGJ", value: 25 },
  { texto: "CGU", value: 26 },
  { texto: "ALEAM - CPI da Saúde", value: 27 },
  { texto: "Petição Advogado", value: 28 },
  { texto: "Camara dos Deputados Federais", value: 29 },
  { texto: "Polícia Federal", value: 30 },
  { texto: "Comitê de Crise - COVID 19", value: 31 },
  { texto: "Câmara Municipal de Manaus", value: 32 },
  { texto: "Conselho Tutelar", value: 33 },
];

/*
export const OrgaosSeeder: Array<Orgaos> = [
  { texto: "DPE", value: "DPE" },
  { texto: "Delegacia de Polícia", value: "DelPolicia" },
  { texto: "FVS", value: "FVS" },
  { texto: "SPA", value: "SPA" },
  { texto: "TCE", value: "TCE" },
  { texto: "MPC", value: "MPC" },
  { texto: "MPE", value: "MPE" },
  { texto: "MPF", value: "MPF" },
  { texto: "MPT", value: "MPT" },
  { texto: "TCU", value: "TCU" },
  { texto: "Ministério da Saúde", value: "Minist.Saude" },
  { texto: "CRM", value: "CRM" },
  { texto: "CEMA", value: "CEMA" },
  { texto: "DPU", value: "DPU" },
  { texto: "Casa Civil", value: "CasaCivil" },
  { texto: "ALEAM", value: "ALEAM" },
  { texto: "SEINFRA", value: "SEINFRA" },
  { texto: "Serviço Social", value: "Serv.Social" },
  { texto: "SEJUSC", value: "SEJUSC" },
  { texto: "SESAI", value: "SESAI" },
  { texto: "HPS Platão Araújo", value: "HPSPlataoAraujo" },
  { texto: "HPS 28 de Agosto", value: "HPS28Agosto" },
  { texto: "PGE", value: "PGE" },
  { texto: "CGE", value: "CGE" },
  { texto: "CGJ", value: "CGJ" },
  { texto: "CGU", value: "CGU" },
  { texto: "ALEAM - CPI da Saúde", value: "ALEAMcpiSaude" },
  { texto: "Petição Advogado", value: "PeticaoADV" },
  { texto: "Camara dos Deputados Federais", value: "CamaraDepFed" },
  { texto: "Polícia Federal", value: "PolFed" },
  { texto: "Comitê de Crise - COVID 19", value: "ComiteCriseCOVID" },
  { texto: "Câmara Municipal de Manaus", value: "CamaraMunManaus" },
  { texto: "Conselho Tutelar", value: "ConselhoTutelar" },
];
*/
             