export type Processo = {
    idProcesso: string,
    numProcedimento: string,
    idTipoProcesso: string,
    prazoTotal: number,
    idOrgaoDemandante: string,
    dataProcesso: string,
    dataRecebimento: string,
    horaRecebimento: string,
    idAssunto: string,
    idClassificacao: string,
    objeto: string,
    requerSIGED: boolean,
    numProcessoSIGED: string,
    dataProcessoSIGED: string,
    permanenciaSIGED: string,
    caixaAtualSIGED: string,
    tramitacaoSIGED: string,
    idResponsavel: string,
    descricao: string,
    dataLimitePrazo: string,
    diasPercorridos: number,
    diasExpirados: number,
    statusPrazo: string,
    statusProcesso: string, 
    sigiloso: string,
    observacao: string,   
};
